server:
  port: 8080

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true

logging:
  level:
    org.springframework.cloud.consul: DEBUG

spring:
  cloud:
    consul:
      discovery:
        preferIpAddress: true
        instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    circuit:
      breaker:
        enabled: true

consumed.microservice.name: "microservice1"

turbine:
  aggregator:
    clusterConfig: microserviceconsumer
  appConfig: microserviceconsumer